// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7J5Z6TCmtQc2w1oG1onVdhFDMpClQwsU',
    appId: '1:776997196139:web:e209dd2b0cd6ff8c08bc2e',
    messagingSenderId: '776997196139',
    projectId: 'chat-app-3c597',
    authDomain: 'chat-app-3c597.firebaseapp.com',
    storageBucket: 'chat-app-3c597.firebasestorage.app',
    measurementId: 'G-LSK857XM1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaaqieT1jDzA-8SgE4LWDMHkxRSm019vo',
    appId: '1:776997196139:android:6e5670b10b9e4ed608bc2e',
    messagingSenderId: '776997196139',
    projectId: 'chat-app-3c597',
    storageBucket: 'chat-app-3c597.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCin6q1vADDt-oxupaEg4UI2nRgM_dvYqQ',
    appId: '1:776997196139:ios:cc0235ffca7d182708bc2e',
    messagingSenderId: '776997196139',
    projectId: 'chat-app-3c597',
    storageBucket: 'chat-app-3c597.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCin6q1vADDt-oxupaEg4UI2nRgM_dvYqQ',
    appId: '1:776997196139:ios:cc0235ffca7d182708bc2e',
    messagingSenderId: '776997196139',
    projectId: 'chat-app-3c597',
    storageBucket: 'chat-app-3c597.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7J5Z6TCmtQc2w1oG1onVdhFDMpClQwsU',
    appId: '1:776997196139:web:64be5ba3dc5b427b08bc2e',
    messagingSenderId: '776997196139',
    projectId: 'chat-app-3c597',
    authDomain: 'chat-app-3c597.firebaseapp.com',
    storageBucket: 'chat-app-3c597.firebasestorage.app',
    measurementId: 'G-E99TPMPHJN',
  );
}
